### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by 0ffz**
Would like to use MIT for this one since it's definitely something others might want to use.

### CODE REVIEW

**Comment by 0ffz** [comment]
@Derongan @Norazan @DevScyu this is a bump to everyone that's contributed a significant portion of code, please comment agreeing to the license change, as do I. 

Put under Derongan's name because it's more legally correct than org name. ~~Don't worry about gradle build failing, it won't on master~~

**Comment by Norazan** [comment]
All fine with me

**Comment by Derongan** [comment]
all fine here

**Review by Derongan — APPROVED** [review]

**Review by DevScyu — APPROVED** [review]
Fine with me :+1:

**Pull request merged**
